bips/bip-1.md
protocol/contracts/farm/InitBip1.sol

- [Summary](#summary)
- [Proposed Solution](#proposed-solution)
- [Proposed Uses of Dev Budget](#proposed-uses-of-dev-budget)
- [Proposed Uses of Marketing Budget](#proposed-uses-of-marketing-budget)
- [Budget Allocation Details](#budget-allocation-details)
- [Proposing](#proposing)
- [Voting](#voting)
- [Passing](#passing)
- [Budget Structural Details](#budget-structural-details)
- [BIP Technical Rationale](#bip-technical-rationale)
- [BIP Economic Rationale](#bip-economic-rationale)
- Mint 120,000 Beans to an initial development budget.
- Mint 80,000 Beans to an initial marketing budget.
- Establish a process for specific allocations of each budget leveraging Snapshot.
- Fund initial proposals to hire a full-time front-end dev and a …

BIP-1: Dev and Marketing Budget

---

bips/bip-8.md
protocol/contracts/farm/AppStorage.sol
protocol/contracts/farm/facets/BudgetFacet.sol
protocol/contracts/farm/init/InitBip8.sol
protocol/contracts/mocks/mockFacets/MockBudgetFacet.sol
protocol/scripts/deploy.js
protocol/test/Budget.test.js

- [Proposer](#proposer)
- [Summary](#summary)
- [Goals](#goals)
- [Structure](#structure)
- [Dividing Line](#dividing-line)
- [Amounts](#amounts)
- [Optimistic Approvals](#optimistic-approvals)
- [Tiered Quorum](#tiered-quorum)
- [Custody](#custody)
- [Initial Allocations](#initial-allocations)
- Mint 1,200,000 Beans to fund Beanstalk Farms to train and retain a set of core contributors through the end of Q1 2022.
- Mint 800,000 Beans to fund Bean Sprout, a new Beanstalk accelerator program to facilitate rapid development on and around Beanstalk in a decentralized fashion, through the end of Q1 2022.
- Allow Beanstalk contributors to elect to sow an arbitrary percentage (0-100%) of their allocated Beans, independent of whether there is a …

Bip 8: 2022 Q1 Budget

---

bips/bip-10.md
protocol/scripts/diamond.js

- [Proposer](#proposer)
- [Summary](#summary)
- [Proposed Solution](#proposed-solution)
- [Payment](#payment)
- [Fundraiser Rationale](#fundraiser-rationale)
- [User Interface](#user-interface)
- Hire Omniscia to perform a continuous code audit on Beanstalk to facilitate the swift proposal of new BIPs by Beanstalk Farms.
- Leverage the "Fundraiser" process proposed in BIP-4 to mint the Beans and raise the USDC necessary to pay for the Omniscia retainer.
- Mint 250,000 Beans and create a Fundraiser to raise 250,000 USDC in exchange for 250,000 Beans. Pay Omniscia 250,000 USDC for the retainer.
- Send 50,000 Beans from Beanstalk Farms to Omnsicia as a down payment, to be returned upon completion of the retainer payment. …

BIP-10: Omniscia Retainer

---

protocol/contracts/libraries/Convert/LibCurveConvert.sol

I'm working on implementing convert functionality into the frontend and found these notes helpful for my own understanding.
For clarity & consistency with other convert functions like `beansToPeg`, this PR renames the output variable of `getBeanAmountOut` from `lp` to `bean`.

Annotate curve convert amountOut functions; rename output var

---

protocol/contracts/libraries/Convert/LibConvert.sol
protocol/contracts/libraries/Convert/LibCurveConvert.sol

Previously this call was reverting with `Convert: Tokens not supported`.
Tested all four conversion modes against a local fork:
```
// BEAN -> BEAN:3CRV
getAmountOut(
0xBEA0000029AD1c77D3d5D23Ba2D8893dB9d1Efab,
0xc9C32cd16Bf7eFB85Ff14e0c8603cc90F6F2eE49,
1000000
) // => "1037291677839082467"
// urBEAN -> urBEAN:3CRV
getAmountOut(
0x1BEA0050E63e05FBb5D8BA2f10cf5800B6224449,
0x1BEA3CcD22F4EBd3d37d731BA31Eeca95713716D,
1000000
) // => "1048437"
// BEAN:3CRV -> BEAN
getAmountOut(
0xc9C32cd16Bf7eFB85Ff14e0c8603cc90F6F2eE49,
0xBEA0000029AD1c77D3d5D23Ba2D8893dB9d1Efab,
1000000000000000000
) // => "963849"
// urBEAN:3CRV -> urBEAN
getAmountOut(
0x1BEA3CcD22F4EBd3d37d731BA31Eeca95713716D,
0x1BEA0050E63e05FBb5D8BA2f10cf5800B6224449,
1000000
) // => "953594"
```

fix: use unripeBeanAddress when converting Unripe BEAN to Unripe LP

---

bips/ebip-0.md
protocol/contracts/libraries/Silo/LibSilo.sol

Per the process outlined in the [BCM Emergency Response Procedures](https://docs.bean.money/governance/beanstalk/bcm-process#emergency-response-procedures), an emergency hotfix may be implemented by an emergency vote of the BCM if the bug is minor and does not require significant code changes.
Note: Bugs or security vulnerabilities qualify as emergencies. Emergency action will not be taken for any reason related to the economic health of Beanstalk (like a bank run, for example).
* GitHub PR: https://github.com/BeanstalkFarms/Beanstalk/pull/80
* GitHub Commit Hash: fa8612e3698d932004f45cd3260c5ad71893b006
* Gnosis Transaction: https://etherscan.io/tx/0x7949bdea1864aa66712bac3d57b79f3030c4cafbb91cdca3d56a0921e1496402
If a Farmer performs an action that removed …

EBIP-0: Emergency BIP-0

---

.gitignore
protocol/foundry.toml
protocol/test/foundry/utils/Deploy.sol

* we deploy a contract to an arbitrary address by combining getCode and [etch](https://book.getfoundry.sh/cheatcodes/etch.html). address.code was not implemented pre 0.8.0, so `at(address _addr)` was added. 
* `at(address _addr)` function gets bytecode at address. 
* cleaned up imports for readability.

updated deploy + cleaned up imports

---

bip-26.md

* Establish a bug bounty program through Immunefi in order to incentivize whitehat hackers to find bugs in Beanstalk.
* Form the Beanstalk Immunefi Committee (BIC) that determines the categorization and payout of bug bounties in accordance with the bug bounty program structure as defined in this BIP.
* Grant the Beanstalk Community Multisig (BCM) the ability to mint up to 3,000,000 Beans in total, in order to execute the will of the BIC. Any increase to this limit must be granted via BIP. 
Security is paramount to Beanstalk's success and a core focus for Beanstalk Farms and Bean Sprout. There is currently no formal program for whitehat hackers to get paid for finding bugs in Beanstalk.
Create a bug bounty program through Immunefi in order to incentivize whitehat hackers to …

BIP-26: Immunefi Bug Bounty Program

---

bug-bounty.md
readme.md

Immunefi suggests adding links to the bug bounty program from the contract repo to increase awareness.

Add bug bounty program links

---

protocol/contracts/farm/facets/MarketplaceFacet/Listing.sol
protocol/test/Marketplace.test.js

Committed: October 25, 2022
---
- [Submitter](#submitter)
- [Emergency Process Note](#emergency-process-note)
- [Links](#links)
- [Solution](#solution)
- [Contract Changes](#contract-changes)
Per the process outlined in the [BCM Emergency Response Procedures](https://docs.bean.money/governance/beanstalk/bcm-process#emergency-response-procedures), an emergency hotfix may be implemented by an emergency vote of the BCM if the bug is minor and does not require significant code changes.
This bug was reported by a whitehat on Immunefi.
- GitHub Commit Hash: [236be8fde5a24cf0189543fea14d5d946b1754f4](https://github.com/BeanstalkFarms/Beanstalk/commit/236be8fde5a24cf0189543fea14d5d946b1754f4)
- [Gnosis …

EBIP-3: Pod Listing Cancellation

---

protocol/abi/Beanstalk.json
protocol/contracts/farm/facets/TokenFacet.sol
protocol/contracts/farm/init/InitEBip5.sol
protocol/contracts/farm/init/InitEBip6.sol
protocol/scripts/ebips.js
protocol/test/Token.test.js

Committed: November 15, 2022
---
- [Submitter](#submitter)
- [Emergency Process Note](#emergency-process-note)
- [Links](#links)
- [Solution](#solution)
- [Contract Changes](#contract-changes)
Per the process outlined in the [BCM Emergency Response Procedures](https://docs.bean.money/governance/beanstalk/bcm-process#emergency-response-procedures), the BCM can take swift action to protect Beanstalk in the event of a bug or security vulnerability.
In the case of EBIP-6, functionality that was removed in [EBIP-4](https://arweave.net/WE73eyNcrbkCSZBAQerylbQ8VAoPjD0HBhVM6-OARVg) and [EBIP-5](https://arweave.net/rihDlnrjmAlFHRmsR3OeP3svGXcxFy_h1dEb0akpylk) is reintroduced this EBIP.
- [GitHub …

EBIP-6: Resolve EBIP-4 and EBIP-5

---

protocol/contracts/tokens/Root.sol
protocol/test/Root.test.js

Committed: November 19, 2022
---
- [Submitter](#submitter)
- [Emergency Process Note](#emergency-process-note)
- [Links](#links)
- [Solution](#solution)
- [Contract Changes](#contract-changes)
Root DAO Multisig (RDM)
Per the process outlined in the [RDM Emergency Response Procedures](https://docs.roottoken.org/governance/root-token/rdm-process#emergency-response-procedures), the RDM can take swift action to protect Root in the event of a bug or security vulnerability.
This bug was reported by a whitehat on Immunefi.
- [GitHub Commit Hash](https://github.com/BeanstalkFarms/Beanstalk/pull/151)
- [Gnosis Transaction](https://app.safe.global/eth:0xb7774ec5031e1d903152E96BbC1601e5D0D83Ca2/transactions/tx?id=multisig_0xb7774ec5031e1d903152E96BbC160 …

fix root redeem

---

protocol/contracts/beanstalk/init/replant/Replant1.sol
protocol/contracts/beanstalk/silo/ConvertFacet.sol
protocol/contracts/beanstalk/silo/SiloFacet/Silo.sol
protocol/contracts/beanstalk/silo/SiloFacet/SiloExit.sol
protocol/contracts/beanstalk/silo/SiloFacet/SiloFacet.sol
protocol/contracts/beanstalk/silo/SiloFacet/TokenSilo.sol
protocol/contracts/libraries/Silo/LibSilo.sol
protocol/contracts/libraries/Silo/LibTokenSilo.sol
protocol/contracts/mocks/mockFacets/MockSiloFacet.sol

- find instances of `_s` or `_season` as parameter names and remove underscore
- remove existing `_season()` function in TokenSilo
- rename the current `season()` function in SiloExit to `_season()`
- See commit history for summary of replacements.

Refactor param & function names in SiloFacet, Lib*Silo

---

protocol/test/Root.test.js

test `reverts if redeem more than owned shares` should revert with `burn amount exceeds balance` rather than `shares is greater than maxRootsIn` since we can set maxRootsIn to the owned shares and pass the test.

Brean root fix

---

projects/subgraph-beanstalk/src/YieldHandler.ts

Update the source data for the Bean EMA used for calculating vAPY to only use the data from the prior 720 seasons (30 days).
Currently up to date on the /beanstalk-dev endpoint.
Deployment ID: `QmaZkM7qCEsxTyC9uxhmgSM3SnzyrKiiPcct1H8iHB56ux`

Subgraph - Update Bean EMA

---

projects/subgraph-beanstalk/src/MarketplaceHandler.ts
projects/subgraph-beanstalk/src/YieldHandler.ts

It is possible to submit a `cancelPodOrder` transaction to Beanstalk for a pod order that was not previously created. As a result an empty `PodOrder` entity was being created. This updates the handler to disregard the cancellation if the order was not previously created, making the expected result from a query `null`.
Resolves #270

Subgraph - Disregard pod orders that are cancelled but don't exist

---

package.json
projects/cli/package.json
projects/cli/src/cli.ts
projects/cli/src/commands/help.ts
projects/cli/src/commands/setprice.ts
projects/cli/src/commands/sunrise.ts

- adds `sunrise`
- adds `setprice`
- updates the way to invoke the cli w/o needing to install it globally: `yarn g:bean` from anywhere in the workspace

CLI: add new commands

---

.github/workflows/ci.protocol.yaml
.github/workflows/ci.sdk.yaml
.github/workflows/ci.subgraph-bean.yaml
.github/workflows/ci.subgraph-beanstalk.yaml
.github/workflows/ci.ui.yaml
.github/workflows/publish-cli.yaml
.github/workflows/publish-sdk.yaml

This PR addresses the new warning in Github to update workflow action versions to use Node16

github: update workflows to use Node16 compatible actions

---

projects/ui/src/components/Common/Form/TokenInputField.tsx
projects/ui/src/components/Swap/Actions/Swap.tsx

The "pathway" system on the Swap page was previously used to identify a swap route between two tokens. A limited number of swap routes were supported: for example the ETH <-> BEAN pair had a route, but USDC <-> DAI did not.
The new Swap router in the SDK handles this internally, and is able to arbitrarily route between tokens as long as an appropriate step is created which defines how to move along a particular token -> token edge. 
Removing the pathway system allows for new swap paths to work out of the box. Screenshot below shows the previously unsupported stable <-> stable pathway.
This PR:

Remove pathway dependency from swap

---

projects/ui/src/components/Balances/SiloBalances.tsx
projects/ui/src/hooks/farmer/useFarmerStalkByToken.ts
projects/ui/src/state/farmer/silo/index.ts
projects/ui/src/state/farmer/silo/updater.ts

Balances page: Fixed calculation of stalk per token - fixes #304
Balances page: Added earned beans to the beans field
Balances page: Slightly tweaked table columns

Fix: Balances page shows correct amount of stalk per token

---

projects/subgraph-beanstalk/src/FieldHandler.ts

Previously the amount of harvested pods was being passed to `updateFieldTotals` as a negative value for `harvestablePods`. This created an incorrect value for `unharvestablePods` on the `Field` entity.
Update the logic within `updateFieldTotals` to subtract harvested pods from the `harvestablePods` total.
Deployment ID: QmU2ixCR9jafGABTwRYQRLwN2y6ZuFVwxoreWsbaJUsYRG
Currently indexing on `/beanstalk-dev`. Now `unharvestablePods + harvestablePods + harvestedPods = podIndex`
Resolves #269

Subgraph Correct field updates on Harvest event

---

projects/sdk/src/lib/silo/Transfer.test.ts

The use of `sunriseForward` in the multi-crate test is creating issues. I am removing that test for now. We have sufficient coverage on unit tests around picking crates, etc.
Concretely, inside the `sunriseForward` util method, we make an `evm_increaseTime` call, followed by an `evm_mine`. I tried to pass a future timestamp to `evm_mine` per https://github.com/foundry-rs/foundry/pull/4041 but that did not solve it. In the future, we can continue exploring this area but for now I don't think it makes sense to chase this issue further.
One change I did make was to reset anvil at the beginning of the test suite and not before each test case. This is how `deposit` tests do it and that does help run time some.

Remove flaky transfer test

---

projects/ui/src/components/Field/PlotSelectDialog.tsx

fix: Clicking the backdrop of a modal or pressing ESC doesn't close it

---

projects/ui/src/components/Analytics/Bean/VolumeChart.tsx
projects/ui/src/components/Analytics/Bean/index.tsx
projects/ui/src/components/Common/Charts/BarChart.tsx
projects/ui/src/components/Common/Charts/BaseSeasonPlot.tsx
projects/ui/src/components/Common/Charts/ChartInfoOverlay.tsx
projects/ui/src/components/Common/Charts/ChartPropProvider.tsx
projects/ui/src/components/Common/Charts/LineChart.tsx
projects/ui/src/components/Common/Charts/QueryState.tsx

There are quite a few prettier formatting change commits, and there are quite a few refactor commits in this PR. When reviewing, please go through each commit individually. I segmented my changes with the reviewer in mind, so that it can be reviewed more easily.
I attached a video demonstrating the bar chart. Notice the season is now a range (ex, `Season  X - Y`). Previously, it was a singular value. This was necessary since I am grouping the data by day (previously it was hourly).
https://user-images.githubusercontent.com/92072158/222723401-a039080b-f921-44bf-bd29-5e9bd175ae25.mp4
Here is a screenshot of the current line chart:

Change Analytic's Volume chart to a bar chart and general improvements

---

.github/workflows/ci.ui.yaml

Updates github action for UI to do a full build, instead of sdk:build and generate. full build includes these as well, plus build will catch typescript errors which are breaking netlify builds lately and are easy to miss in reviews

ui: build during CI

---

projects/ui/src/components/App/muiTheme.ts
projects/ui/src/components/Barn/MyFertilizer.tsx
projects/ui/src/components/Barn/RemainingFertilizer.tsx
projects/ui/src/components/Common/Form/FieldWrapper.tsx
projects/ui/src/components/Common/Stat.tsx
projects/ui/src/components/Field/FieldConditions.tsx
projects/ui/src/components/Silo/RewardItem.tsx

Addressing some UX issues that have been brought up recently
Popups no longer instantly react to touch, needing a longer touch to open
Popups close themselves shortly after the touch event
Moved some popups so they appear above the button (and thus above the user's finger) on mobile

Tweaked popup positioning and behavior on mobile

---

projects/sdk/src/lib/farm/actions/WellSwap.ts
projects/sdk/src/utils/index.ts

Deadline was added to the wells contract calls, and we added to the wells SDK here https://github.com/BeanstalkFarms/Beanstalk/pull/382 but now need to update the beanstalk SDK farm wells swap actions

Add deadline to farm wellswap actions

---

.github/workflows/ci.dex-ui.yaml
projects/dex-ui/.env.production
projects/dex-ui/codegen.ts
projects/dex-ui/graphql.schema.json
projects/dex-ui/package.json
projects/dex-ui/src/components/App/Wrapper.tsx
projects/dex-ui/src/pages/Well.tsx
projects/dex-ui/src/pages/Wells.tsx
projects/dex-ui/src/queries/GetWellSwaps.graphql
projects/dex-ui/src/wells/subgraphFetch.ts
projects/dex-ui/src/wells/useWell.tsx
projects/dex-ui/src/wells/useWellSwaps.tsx
projects/dex-ui/src/wells/useWells.tsx
yarn.lock

Initial subgraph setup for dex-ui:
- Add apollo client
- Configure graphql-cli codegen
- Create the initial GetWellSwaps query
- Wire up a simple demo of the useWellSwaps hook

Dex-ui subgraph configuration and GetWellSwaps query

---

projects/subgraph-wells/schema.graphql
projects/subgraph-wells/src/BeanstalkHandler.ts
projects/subgraph-wells/src/templates/AquiferHandler.ts
projects/subgraph-wells/src/utils/Aquifer.ts
projects/subgraph-wells/subgraph.yaml

This adds a Beanstalk datasource to the Wells subgraph purely to use the `Sunrise` event as a trigger to check if any Well entity needs to have an hourly or daily snapshot taken.

Trigger subgraph snapshots using Sunrise event

---

projects/ui/src/components/Common/MarkdownWrapper.tsx
projects/ui/src/pages/governance/proposal.tsx

Fixed small images being stretched to maximum width 
Fixed proposal column sometimes being too wide and pushing the votes component to the bottom of the page

Fixing issues seen in the BIP-34 proposal page

---

projects/subgraph-wells/schema.graphql

Now that we are manually populating the list of wells deployed by an aquifer rather than using a derived field, this entity can no longer be flagged as immutable.

Remove immutable from Aquifer entity

---

projects/subgraph-wells/src/utils/Well.ts

Only update USD balances if a well contains the BEAN token, otherwise leave at the default value of zero.

Subgraph - Only Update USD for Wells with BEAN

---

projects/ui/src/components/Analytics/Bean/Price.tsx
projects/ui/src/components/Common/Charts/BaseSeasonPlot.tsx
projects/ui/src/components/Common/Charts/ChartInfoOverlay.tsx
projects/ui/src/components/Common/Charts/ChartPropProvider.tsx
projects/ui/src/components/Common/Charts/MultiLineChart.tsx
projects/ui/src/components/Common/Charts/SeasonPlot.tsx
projects/ui/src/components/Common/Charts/StackedAreaChart.tsx
projects/ui/src/components/Common/Stat.tsx
projects/ui/src/components/Silo/Overview.tsx
projects/ui/src/components/Silo/OverviewPlot.tsx

Added Date/Time display to a number of charts, by default it shows the date and time of the last season, updates on hover
Addresses Issue #427

Show date/time on charts

---

projects/ui/src/components/Silo/Actions/Withdraw.tsx
projects/ui/src/util/Actions.ts

Fixed text displayed in the Transaction Details component when user is receiving Stalk but losing Seeds
Fixed the Withdraw Transaction Details to correctly indicate that the user is losing seeds/stalk.

Silo Transaction Details - Copy fixes

---

projects/sdk/src/lib/farm/actions/AddLiquidity.ts
projects/sdk/src/lib/farm/actions/ClaimWithdrawal.ts
projects/sdk/src/lib/farm/actions/ClaimWithdrawals.ts
projects/sdk/src/lib/farm/actions/Deposit.ts
projects/sdk/src/lib/farm/actions/Exchange.ts
projects/sdk/src/lib/farm/actions/ExchangeUnderlying.ts
projects/sdk/src/lib/farm/actions/PermitERC20.ts
projects/sdk/src/lib/farm/actions/RemoveLiquidityOneToken.ts
projects/sdk/src/lib/farm/actions/TransferDeposit.ts
projects/sdk/src/lib/farm/actions/TransferDeposits.ts
projects/sdk/src/lib/farm/actions/TransferToken.ts
projects/sdk/src/lib/farm/actions/UnwrapEth.ts
projects/sdk/src/lib/farm/actions/WithdrawDeposit.ts
projects/sdk/src/lib/farm/actions/WithdrawDeposits.ts
projects/sdk/src/lib/farm/actions/WrapEth.ts
projects/sdk/src/lib/swap/Swap.estimates.test.ts
projects/sdk/src/lib/swap/Swap.test.ts
projects/sdk/src/lib/swap/graph.test.ts
projects/sdk/src/lib/swap/graph.ts
projects/sdk/src/utils/index.ts

1. Adds two helper functions to create bi-directional edges for the following cases:
a. Exchanging between two tokens in a pool
b. Moving from an underlying token -> LP token via AddLiquidity, and vice-versa via RemoveLiquidityOneToken
2. Adds tests for the helpers to ensure both edges (A -> B _and_ B -> A) are accounted for
3. Introduces tests for some route paths where we want to ensure the router takes the most direct path. Notably:
a. 3CRV -> underlying should always remove liquidity, and vice-versa
b. Stables in 3pool should swap directly on 3pool, no intermediate hops
4. Add helper `expectInstanceOf` which is the same as expect.instanceOf` but with a Typescript assertion so any following context is aware of the assertion
5. Change all action constructor parameters to `public …

Swap Router Fixes & Improvements

---

projects/sdk/src/lib/farm/actions/AddLiquidity.ts
projects/sdk/src/lib/farm/actions/ClaimWithdrawal.ts
projects/sdk/src/lib/farm/actions/ClaimWithdrawals.ts
projects/sdk/src/lib/farm/actions/Deposit.ts
projects/sdk/src/lib/farm/actions/Exchange.ts
projects/sdk/src/lib/farm/actions/ExchangeUnderlying.ts
projects/sdk/src/lib/farm/actions/PermitERC20.ts
projects/sdk/src/lib/farm/actions/RemoveLiquidityOneToken.ts
projects/sdk/src/lib/farm/actions/TransferDeposit.ts
projects/sdk/src/lib/farm/actions/TransferDeposits.ts
projects/sdk/src/lib/farm/actions/TransferToken.ts
projects/sdk/src/lib/farm/actions/UnwrapEth.ts
projects/sdk/src/lib/farm/actions/WithdrawDeposit.ts
projects/sdk/src/lib/farm/actions/WithdrawDeposits.ts
projects/sdk/src/lib/farm/actions/WrapEth.ts
projects/sdk/src/lib/swap/Swap.test.ts
projects/sdk/src/lib/swap/graph.test.ts
projects/sdk/src/lib/swap/graph.ts
projects/sdk/src/utils/index.ts
projects/ui/src/components/Swap/Actions/Transfer.tsx

**DO NOT MERGE** until approval of #469.
Adds a red warning to the Transfer page if the user is delivering assets to the Farm balance of some other account.
The recipient will need access to the Farm balance to use the assets. Transferring to an account like a Coinbase exchange wallet will cause a loss of funds.

Transfer: Farm balance warning

---

projects/ui/src/components/Common/Charts/LineChart.tsx
projects/ui/src/components/Common/Charts/MultiLineChart.tsx
projects/ui/src/components/Common/Charts/StackedAreaChart.tsx
projects/ui/src/components/Field/FieldConditionsHeader.tsx

Charts will now display a suitable amount of x-axis ticks according to the chart's width
Added shorter copy for the Field Conditions header on mobile

Mobile - Chart + Copy tweaks

---

projects/ui/src/components/Barn/Actions/Buy.tsx
projects/ui/src/components/Field/Actions/Sow.tsx
projects/ui/src/components/Silo/Actions/Deposit.tsx
projects/ui/src/components/Swap/Actions/Transfer.tsx

Now we only prompt the user for an approval if:
- Circulating Balance is selected
- Combined Balance is selected and the amount is higher than the Farm Balance
Addresses issue #478

Improved approval checks

---

protocol/abi/Beanstalk.json
protocol/hardhat.config.js
protocol/package.json

The prior ABI generation code wasn't designed to locate files like `contracts/beanstalk/silo/SiloFacet/LegacyClaimWithdrawalFacet.sol`. This change automatically finds all *Facet.sol files with globs and correctly resolves their ABIs. I also switched to path.join() to support Windows paths.
```
npx hardhat diamondABI
barn:      contracts/beanstalk/barn/UnripeFacet.sol
event AddUnripeToken
event ChangeUnderlying
event Chop
event Pick
function _getPenalizedUnderlying
function addUnripeToken
function balanceOfPenalizedUnderlying
function balanceOfUnderlying
function chop
function getPenalizedUnderlying
function getPenalty
function getPercentPenalty
function getRecapFundedPercent
function getRecapPaidPercent
function getTotalUnderlying
function getUnderlying
function …
```

fix: include *Facet.sol in ABI

---

projects/sdk/src/lib/farm/actions/ClaimWithdrawal.ts
projects/sdk/src/lib/farm/actions/ClaimWithdrawals.ts
projects/sdk/src/lib/farm/actions/WithdrawDeposit.ts
projects/sdk/src/lib/farm/actions/WithdrawDeposits.ts
projects/sdk/src/lib/farm/actions/index.ts
projects/sdk/src/lib/silo.test.ts
projects/sdk/src/lib/silo.ts
projects/sdk/src/lib/silo/Withdraw.ts
projects/sdk/src/lib/tokens.ts
projects/ui/src/lib/Txn/FarmSteps/silo/ClaimFarmStep.ts
projects/ui/src/lib/Txn/FarmSteps/silo/MowFarmStep.ts

1. After this PR, `yarn all:build` is running again.
2. Updates Mow functionality to accept tokens with sensible defaults; adds support for the new `mowAndMigrate` function
3. Updates withdrawDeposit(s) to have `toMode` parameter associated with zero withdraw upgrade

Fix contract functions

---

projects/sdk/src/lib/events/processor.test.ts
projects/sdk/src/lib/events/processor.ts
projects/ui/src/state/beanstalk/field/index.ts
projects/ui/src/state/farmer/field/index.ts
projects/ui/src/state/farmer/field/updater.ts
projects/ui/src/util/BigNumber.ts

Reintroduce the Field event processor; migrate from the previous BigNumberJS & object approach to ethers.BigNumber and Maps.
Reintroduce helper function parsePlots to split plots into harvestable & non-harvestable. Add test for this.
Use the processor in the farmer/field/updater and wrangle the ethers.BigNumbers into BigNumberJS which is what the UI components expect currently. Not pretty but functional. Tested manually on some of my accounts.
`yarn run jest processor.test`

Event processor: Field

---

protocol/abi/Beanstalk.json
protocol/contracts/beanstalk/silo/ConvertFacet.sol
protocol/contracts/beanstalk/silo/SiloFacet/SiloExit.sol
protocol/hardhat.config.js
protocol/scripts/check-events.js

```
$ node ./scripts/check-events.js
Searching:  contracts/beanstalk/**/*Facet.sol 23
Event mismatch {
new: {
indexed: false,
internalType: 'int96',
name: 'stem',
type: 'int96'
},
existing: {
indexed: false,
internalType: 'int128',
name: 'stem',
type: 'int128'
}
}
```
```
$ node ./scripts/check-events.js
Searching:  contracts/beanstalk/**/*Facet.sol 23
Map(46) {
'Incentivization' => [ 'contracts/beanstalk/sun/SeasonFacet/SeasonFacet.sol' ],
'Reward' => [ 'contracts/beanstalk/sun/SeasonFacet/SeasonFacet.sol' ],
'SeasonOfPlenty' => [ 'contracts/beanstalk/sun/SeasonFacet/SeasonFacet.sol' ],
'Soil' => [ 'contracts/beanstalk/sun/SeasonFacet/SeasonFacet.sol' ],
'Sunrise' => [ 'contracts/beanstalk/sun/SeasonFacet/SeasonFacet.sol' ],
'WeatherChange' => [ …
```

Fix Convert's `RemoveDeposit` event

---

projects/ui/src/lib/Beanstalk/Silo/Convert.ts
projects/ui/src/lib/Beanstalk/Silo/Utils.ts

Since LP deposits can have varying BDV, the best option for the Farmer during a convert is to increase the BDV of their existing lowest-BDV crates.
The UI currently selects crates to convert purely on the basis of this ratio. However, if the `bdv/amount` ratio is similar for two crates, it is optimal for the farmer to select the crate with the higher season pre-Silo V3 to minimize potential stalk loss, since older crates can't be converted into seasons less than 1.
This PR upgrades the selection function to prioritize `amount/bdv` ratio up to 4 decimal places. If two crates have the same ratio to 4 decimal places, the selection process sorts more recent deposits first.

UI: When converting, ignore small ratio diffs and prioritize Season

---

projects/subgraph-beanstalk/src/SiloHandler.ts

Properly update the total amount of tokens for withdrawal if a farmer submits two withdrawals within the same season.

Subgraph - Withdrawal crate total

---

projects/dex-ui/src/components/BottomDrawer.tsx
projects/dex-ui/src/pages/Well.tsx
projects/ui/src/components/Balances/Header.tsx

Layout of "Stalk, Seeds, Pods, Sprouts" on Balances is a bit off.
- moved Stalk HeaderItem into inner Row
- added VerticalDivider
"Stalk, Seeds, Pods, Sprouts" now centered, and (added bonus) I can now see Stalk tool-tip text on hover.

Bean UI  - balances header.tsx layout adjustment

---

projects/dex-ui/src/components/Frame/Footer.tsx
projects/dex-ui/src/pages/Home.tsx
projects/dex-ui/src/pages/Liquidity.tsx
projects/dex-ui/src/pages/Wells.tsx
projects/dex-ui/src/tokens/TokenProvider.tsx

Removed loading screen
Added hover state to all buttons

Basin UI - Small fixes

---

projects/dex-ui/src/components/Well/Activity/eventRender.tsx
projects/dex-ui/src/components/Well/Chart/ChartSection.tsx
projects/dex-ui/src/queries/GetWellChartData.graphql
projects/dex-ui/src/wells/chartDataLoader.ts

Fixed chart only fetching up to 100 data points per query
Added logic to handle more than 1000 data points (in practice, only applicable when selecting "ALL")
Changed default time period to "1 WEEK"

Basin UI - Chart updates

---

projects/ui/src/components/Nav/Buttons/SunButton.tsx

Icon will now change based on whether Beans were minted in the currently displayed season or not

Bean UI - Season button tweak

---

projects/subgraph-bean/schema.graphql
projects/subgraph-bean/src/Bean3CRVHandler.ts
projects/subgraph-bean/src/Bean3CRVHandler_V1.ts
projects/subgraph-bean/src/BeanWellHandler.ts
projects/subgraph-bean/src/BeanstalkHandler.ts
projects/subgraph-bean/src/UniswapV2Handler.ts
projects/subgraph-bean/src/utils/Cross.ts
projects/subgraph-bean/src/utils/Pool.ts

Previously there was only one pool to track peg crosses, and the overall Bean peg was tied to that one pool. With the introduction of the Bean:ETH well, the overall Bean price can cross peg independently of an individual pool have a cross at the same time.
Schema changes:
- `Cross` entity removed and replaced by the following two entities
- `BeanCross` entity added to track the overall Bean peg cross. This uses the liquidity weighted price returned by the current price contract.
- `PoolCross` entity added to track individual peg crosses within a pool. Each pool has their own incremental counter for the number crosses observed.

Bean Subgraph - Split Cross Entity

---

projects/subgraph-basin/src/WellHandler.ts

Both the `updateWellVolumes` and `updateWellTokenBalances` functions update the overall reserves of the well based on amounts emitted by the events. This introduced a bug where when a `Shift` event is emitted with the new absolute reserve values the input amounts were incorrect if a `RemoveLiquidityOneToken` event was processed prior.
New deployment id: QmQYnky1aQahppvTti18QShu7PS47DTPxVH7Y8CV8TSrxA

Subgraph - Basin: Remove single token reserves update

---

projects/subgraph-bean/src/BeanWellHandler.ts

Update the volume calculation to use either the bean amount * current well price or current price in bean * current well price for single sided liquidity removals.
Previously any changes in liquidity USD value due to ETH movement would be included in volume if there had not been any activity prior to calculating the volume on the removal.

Subgraph - Bean: Fix volume calculation for single sided removals

---

projects/subgraph-bean/src/utils/Bean.ts
projects/ui/src/components/Analytics/Bean/LiquiditySupplyRatio.tsx

Include all of the Beans held within the pools to the liquidity to supply ratio prior to replant.

Include v1 BEAN3CRV and BEANLUSD in liquidity to supply calc

---

projects/subgraph-bean/src/BeanstalkHandler.ts

Formerly only the BEAN price was being updated on each sunrise. Now include and update the delta liquidity in USD for the case that there was no activity within the season to trigger the updates through the pool handlers.

Update liquidity USD values on sunrise

---

projects/dex-ui/src/components/ActionWalletButtonWrapper.tsx
projects/dex-ui/src/components/ConnectWalletButton.tsx
projects/dex-ui/src/components/Liquidity/AddLiquidity.tsx
projects/dex-ui/src/components/Liquidity/RemoveLiquidity.tsx
projects/dex-ui/src/components/Swap/SwapRoot.tsx
projects/dex-ui/src/pages/Home.tsx

updates: 
- Enable connect wallet on other pages
- Fix homepage height being cut off when browser height is too small

Basin UI - Fix home height + Fix connect wallet disabled

---

projects/subgraph-bean/src/utils/Bean.ts
projects/subgraph-bean/src/utils/Cross.ts

When checking for a pool cross, the wrong value was being passed in to load the snapshots. Pass the pool address instead of the bean address to correct.

Bean subgraph: Correct pool cross handler

---

projects/sdk/src/lib/BeanstalkSDK.ts
projects/sdk/src/lib/contracts.ts
projects/sdk/src/lib/events/EventManager.ts
projects/ui/src/components/App/SdkProvider.tsx
projects/ui/src/graph/client.ts

This change adds a read only provider to the beanstalk SDK which allows the UI (or other consumers) to implement a different provider for read-only operations.
Specifically, this allows us to configure the UI to read silo balances using this provider, and this provider will be set to use BeanstalkFarms' Alchemy account... meaning no more RPC limit errors for users who have wallets/providers with low limits.

Implement read-only provider

---

projects/sdk/src/lib/swap/Swap.ts
projects/sdk/src/lib/swap/SwapOperation.ts
projects/ui/src/components/Chop/Actions/Chop.tsx
projects/ui/src/components/Common/Form/BalanceFromRow.tsx
projects/ui/src/components/Common/Form/TokenSelectDialog.tsx
projects/ui/src/components/Market/PodsV2/Actions/Buy/CreateOrder.tsx
projects/ui/src/components/Market/PodsV2/Actions/Buy/FillListingForm.tsx
projects/ui/src/components/Swap/Actions/Swap.tsx

Update token input fields 

---

protocol/contracts/beanstalk/silo/SiloFacet/Silo.sol
protocol/contracts/beanstalk/silo/SiloFacet/SiloExit.sol
protocol/contracts/beanstalk/silo/SiloFacet/SiloFacet.sol
protocol/contracts/beanstalk/sun/SeasonFacet/Sun.sol
protocol/contracts/libraries/Silo/LibLegacyTokenSilo.sol
protocol/contracts/libraries/Silo/LibSilo.sol
protocol/hardhat.config.js
protocol/scripts/ebips.js
protocol/test/Silo.test.js
protocol/test/SiloToken.test.js

Committed: February 5, 2024
---
- [Submitter](#submitter)
- [Summary](#summary)
- [Links](#links)
- [Solution](#solution)
- [Contract Changes](#contract-changes)
* As a result of a potential attack vector around stealing Earned Beans during the Vesting Period:
* Remove the Vesting Period logic altogether; and
* Upgrade `withdrawDeposit(s)` to revert when called during the first 10 blocks of a Season.
Per the process outlined in the [BCM Emergency Response Procedures](https://docs.bean.money/almanac/governance/beanstalk/bcm-process#emergency-response-procedures), the BCM can take swift action to protect Beanstalk in the event of a bug or security vulnerability.
- [EBIP-14 GitHub …

EBIP-14: Remove Vesting Period

---

protocol/abi/Beanstalk.json
protocol/contracts/beanstalk/AppStorage.sol
protocol/contracts/beanstalk/init/InitBipSeedGauge.sol
protocol/contracts/beanstalk/init/InitWhitelistStatuses.sol
protocol/contracts/beanstalk/silo/WhitelistFacet/WhitelistFacet.sol
protocol/contracts/beanstalk/silo/WhitelistFacet/WhitelistedTokens.sol
protocol/contracts/libraries/Silo/LibWhitelist.sol
protocol/contracts/libraries/Silo/LibWhitelistedTokens.sol
protocol/contracts/mocks/MockInitDiamond.sol
protocol/contracts/mocks/mockFacets/MockWhitelistFacet.sol
protocol/test/Season.test.js
protocol/test/Sun.test.js
protocol/test/Weather.test.js
protocol/test/Whitelist.test.js

Introduce a list of Whitelist Statuses in `AppStorage.sol`. This list is managed by `LibWhitelistedTokens.sol`. A token's Whitelist Status is set when it is whitelisted. A token's status is changed when dewhitelisted. Removing a token from the Whitelist Status must be manual. `WhitelistFacet` now inherits `WhitelistedTokens.sol`, which contain `view` functions to read the lists provided by `LibWhitelistedTokens.sol`.

Add dynamic Whitelist Status list

---

protocol/contracts/libraries/LibGauge.sol

- use `gpPerBdv = 0` when there is 0 Deposited Bdv.

`gpPerBdv = 0` when 0 Deposited Bdv

---

PROPOSALS.md

*"People tend to overestimate what can be done in one year and to underestimate what can be done in five or ten years." - J. C. R. Licklider, 1965*
Proposer Wallet: [0xf9d183af486a973b7921ceb5fdc9908d12aab440](https://etherscan.io/verifySig/35848)
* Mint 500,000 Beans to fund Beanstalk Farms to retain, grow and support a group of contributors to Beanstalk through the end of H1 2024;
* Mint 500,000 Beans to fund Beanstalk Farms through the end of H2 2024;
* Mint 450,000 Beans to the Security Fund (f.k.a. Audit Fund); and
* Maintain the DAO's ability to withhold Beanstalk Farms' H2 funding after the end of H1 with an appropriate governance structure.
* [BIP-40 GitHub PR](https://github.com/BeanstalkFarms/Beanstalk/pull/770)
* [Safe …

BIP-40: Beanstalk Farms 2024 Development Budget

---

projects/ui/src/util/wagmi/ethersAdapter.ts

sdk was getting re-initialized on every useSDK() call. traced it down to this useMemo dependency that wasn't right.

ui: fix sdk re-init issue (ticket 32)

---

protocol/contracts/beanstalk/silo/ConvertFacet.sol
protocol/contracts/beanstalk/silo/EnrootFacet.sol
protocol/contracts/beanstalk/silo/SiloFacet/TokenSilo.sol
protocol/contracts/beanstalk/sun/SeasonFacet/SeasonFacet.sol
protocol/contracts/libraries/LibEvaluate.sol
protocol/contracts/libraries/Silo/LibGerminate.sol
protocol/contracts/libraries/Silo/LibTokenSilo.sol
protocol/contracts/libraries/Silo/LibWhitelist.sol
protocol/contracts/libraries/Well/LibWell.sol
protocol/contracts/mocks/mockFacets/MockSeasonFacet.sol
protocol/test/Sun.test.js

Adds recommended remediations based on Cyfrin review. 
- Updated LibGerminate.EndTotalGermination to emit the proper season: https://github.com/BeanstalkFarms/Beanstalk/pull/829/commits/1f29edda1d63a00231ff80a45d7284f6d81d1b02#diff-d2261445685829aad9421eae03f9644ae9d11be5713ccc0870497a0be1e58d8aL121 
- Updated NatSpec of LibTokenSilo::addDepositToAccount: https://github.com/BeanstalkFarms/Beanstalk/pull/829/commits/6429ce199ea3b60f9b43d6072a59689912abbf15#diff-a0abb2f4046ee1f0caff2716c2c0a21755aa0eac99ab5e6519fcb77d989a196cL307 (Ignore the tab, fixed in a later commit). 
- Downcasted bdv in convertFacet, line 238: https://github.com/BeanstalkFarms/Beanstalk/pull/829/commits/2914b1984d934e188f5d8f60f115fff855505a81#diff-80dee2bf35b86cb246d17e5c125566d999c1c76f695851906d62df8db8930950R237
- …

seedGauge-remediation-fix

---

protocol/contracts/C.sol
protocol/contracts/beanstalk/farm/TractorFacet.sol
protocol/contracts/libraries/LibFarm.sol
protocol/contracts/libraries/LibTractor.sol

Reacting to old comments in #727

varied tractor cleanups

---

protocol/contracts/libraries/LibLockedUnderlying.sol
protocol/test/Gauge.test.js

The current seed gauge implementation incorrectly calculates the locked beans underlying an unripe bean(how Beanstalk accounts for Unripe in the L2SR calculation). The issue occurs when the Unripe supply is <10M and in these instances Beanstalk would've calculated a lower L2SR than intended.

Lib locked underlying fix

---

protocol/abi/Beanstalk.json
protocol/contracts/beanstalk/barn/UnripeFacet.sol
protocol/contracts/libraries/LibFertilizer.sol
protocol/contracts/libraries/LibLockedUnderlying.sol
protocol/contracts/libraries/LibUnripe.sol
protocol/contracts/mocks/mockFacets/MockUnripeFacet.sol
protocol/hardhat.config.js
protocol/scripts/bips.js
protocol/test/BeanEthToBeanWstethMigration.test.js
protocol/test/Gauge.test.js
protocol/test/LockedBeansMainnet.test.js
protocol/test/SeedGaugeMainnet.test.js
protocol/test/Unripe.test.js

Update liblockedUnderlying.
Uses `LibUnripe.getTotalRecapitalizedPercent()` instead of `LibUnripe.getRecapPaidPercentAmount`.
- fixes various view functions
- skipped legacy tests
- fixed various tests
- added mainnet tests.

remediations 2.

---

projects/ui/.eslintrc.js

Add rule to ignore eslint errors caused by the css prop on DOM elements
https://emotion.sh/docs/eslint-plugin-react

Bean UI - Update eslint rules

---

protocol/contracts/beanstalk/barn/UnripeFacet.sol
protocol/contracts/libraries/Convert/LibChopConvert.sol
protocol/contracts/libraries/Convert/LibConvert.sol
protocol/contracts/libraries/Convert/LibConvertData.sol
protocol/contracts/libraries/LibChop.sol
protocol/contracts/libraries/LibUnripe.sol
protocol/test/ConvertUnripe.test.js
protocol/test/utils/encoder.js

Introduce the ability for users to convert unripe assets into their ripe counterpart.
Currently, the only way to redeem unripe assets is by withdrawing from the silo, and calling `chop()`. This creates an inefficiency in which users wanting to redeem early lose the opportunity cost associated with grown stalk. In light of the unripe seed rewards changing, allowing users to redeem their unripe assets without losing stalk allows farmers to weigh stalk growth vs higher redemption %. 
- Add new convert type in `LibDataConvert` :heavy_check_mark:
- Modified `LibConvert` to include new convert type :heavy_check_mark:
- Implemented `LibChop` and modified `chop(...)` and `_getPenalizedUnderlying(...) ` to use `LibChop` :heavy_check_mark:
- Implemented `LibChopConvert`  with the …

[INCLUDED IN GAUGE] Unripe λ → λ Conversions

---

projects/ui/src/components/Silo/SiloAssetOverviewCard.tsx
projects/ui/src/components/Silo/SiloCarousel.tsx
projects/ui/src/pages/silo/token.tsx
projects/ui/src/util/Guides.ts

* add note on carousel about seeds on non-unripe whitelisted assets
* remove carousel altogether for dewhitelisted bean3crv
***
* remove vAPY card on bean3crv
***
* remove How to Claim Withdrawals card with broken link

UI: silo cosmetic updates

---

protocol/README.md

Adds note in `protocol/README.md` about compatible node/npm versions.
The other spacing modifications appear to be from auto-format.

Update readme to include known working node/npm versions

---

projects/subgraph-basin/schema.graphql
projects/subgraph-basin/src/utils/VolumeCP.ts
projects/subgraph-basin/src/utils/Well.ts
projects/subgraph-basin/tests/Liquidity.test.ts

Adds a new field that tracks trade reserves in terms of both tokens, not just the bought token. This information is required for coingecko integration, and being able to use this field directly is cleaner than the prior implementation and more generalizable for wells having tokens with unknown prices

[Subgraph-Basin] Add field for cumulative trade reserves of both tokens

---

projects/subgraph-bean/schema.graphql
projects/subgraph-bean/src/BeanstalkHandler.ts
projects/subgraph-bean/src/constants/PooledTokens.ts
projects/subgraph-bean/src/utils/Bean.ts
projects/subgraph-bean/src/utils/Pool.ts
projects/subgraph-bean/src/utils/Token.ts
projects/subgraph-bean/tests/Cross.test.ts
projects/subgraph-bean/tests/Pool.test.ts
projects/subgraph-core/utils/Decimals.ts

- Add `name` field to `Token` entity
- Associate `Token` entity to `Pool` entity
- Add `chain` and `beanstalk` properties to `Bean` entity

[Bean Subgraph] Metadata updates

---

protocol/contracts/libraries/Convert/LibUnripeConvert.sol
protocol/contracts/libraries/LibBarnRaise.sol
protocol/contracts/libraries/LibFertilizer.sol
protocol/contracts/libraries/Oracle/LibOracleHelpers.sol
protocol/contracts/libraries/Oracle/LibUsdOracle.sol
protocol/contracts/libraries/Oracle/LibWstethEthOracle.sol
protocol/test/WstethOracle.test.js

Audit results: https://www.codehawks.com/report/clu7665bs0001fmt5yahc8tyh
Remediation: Modified `getWstethEthPrice` function to include explicit logic for handling the case where the percent difference between the Chainlink and Uniswap prices is greater then `MAX_DIFFERENCE`. 4a7ad83345027ac4622748cf05aab43aa9006bea
Original finding: https://www.codehawks.com/report/clu7665bs0001fmt5yahc8tyh#M-02
Remediation: Modified `getPercentDifference` to ensure divisor is always lower so that percent differences calculated are consistent no matter the input order. f453c547c29600c77b92f6abe329f4e7d175a023
Original finding: https://www.codehawks.com/report/clu7665bs0001fmt5yahc8tyh#M-03
Remediation: Modified totalDollars variable calculation as suggested: 0c7fe76cea1f8f0e0f712d1dcdaba8f3f683f720 …

wstETH Migration Remediations

---

protocol/contracts/beanstalk/sun/SeasonFacet/Sun.sol
protocol/contracts/libraries/LibUnripe.sol
protocol/test/Sun.test.js
protocol/test/Unripe.test.js

Audit results: https://www.codehawks.com/report/clvo5kwin00078k6jhhjobn22
Remediation: Set `getTotalRecapitalizedPercent` to 1e6 when beanstalk is fully recapitalized. 00ad54a03c151c722043e8118084beb3cbd401d5
Original finding: https://www.codehawks.com/report/clvo5kwin00078k6jhhjobn22#L-01
Remediation: Modified `getPenalizedUnderlying ` to return `underlyingAmount.mul(s.recapitalized).div(totalUsdNeeded).mul(amount).div(supply)` (given at 100% recapitalization, s.recapitalized/totalUsdNeeded == 1) fae3d9733ee91980aa96f55eda53f99fb316cc02
Original finding:https://www.codehawks.com/report/clvo5kwin00078k6jhhjobn22#L-02
Remediation: check that instDeltaB is negative prior to taking the minimum between instDeltaB and twaDeltaB 77427749c58ab000162e0921ccd4cbd229a12fc2
Original finding: …

Misc Improvements (Codehawks Part 3) Remediations

---

projects/subgraph-basin/schema.graphql
projects/subgraph-basin/src/templates/AquiferHandler.ts
projects/subgraph-basin/src/utils/Well.ts
projects/subgraph-basin/subgraph.yaml

The `tokens` field on the `Well` entity is sorted by token id when queried via the graphql api. This is a problem because the caller can't determine what is the order of tokens in the well. An additional field `tokenOrder` is added here.

Basin subgraph - add token order field

---

protocol/contracts/beanstalk/migration/L1TokenFacet.sol

updates the L1TokenFacet to not use C.sol (as that will be updated with new constants upon the deployment of beanstalk).

remove C.sol from L1TokenFacet

---

protocol/contracts/beanstalk/migration/BeanL2MigrationFacet.sol

Removes the C.sol dependency (given that C.sol will be updated for an L2).

remove C.sol from contract.

---

protocol/contracts/beanstalk/field/FieldFacet.sol
protocol/contracts/beanstalk/init/reseed/L2/ReseedSilo.sol
protocol/contracts/beanstalk/market/MarketplaceFacet/PodTransfer.sol
protocol/contracts/beanstalk/silo/SiloFacet/SiloGettersFacet.sol
protocol/contracts/beanstalk/storage/Account.sol
protocol/contracts/interfaces/IMockFBeanstalk.sol
protocol/contracts/libraries/LibDibbler.sol
protocol/contracts/libraries/Silo/LibTokenSilo.sol
protocol/test/foundry/silo/Silo.t.sol

Fixes 
- [M-14](https://codehawks.cyfrin.io/c/2024-05-beanstalk-the-finale/s/379)
- [M-03](https://codehawks.cyfrin.io/c/2024-05-beanstalk-the-finale/s/491)
by adding a mapping for the silo and field, that allows for O(1) lookup in the depositIdList and plotIndex array.
- `mapping(uint256 => uint256) idIndex;` 
- `mapping(uint256 => uint256) piIndex;`
When a new entry is added to the list, the mapping stores the index. When an entry is removed, the index is set to max (as it should not exist).

add mapping.

---

protocol/contracts/libraries/LibDibbler.sol

Fixes:
[L-17](https://codehawks.cyfrin.io/c/2024-05-beanstalk-the-finale/s/485)
Adds a requirement that the pods sown must be greater than 0. Given that sowing 0 soil should not do anything, this change loses no utility.

Sow - plot index

---

protocol/abi/MockBeanstalk.json
protocol/contracts/C.sol
protocol/contracts/beanstalk/init/InitalizeDiamond.sol
protocol/contracts/beanstalk/migration/L1AppStorage.sol
protocol/contracts/beanstalk/silo/EnrootFacet.sol
protocol/contracts/beanstalk/silo/WhitelistFacet/WhitelistFacet.sol
protocol/contracts/beanstalk/storage/System.sol
protocol/contracts/interfaces/IMockFBeanstalk.sol
protocol/contracts/libraries/Silo/LibGerminate.sol
protocol/contracts/libraries/Silo/LibLegacyWhitelist.sol
protocol/contracts/libraries/Silo/LibSilo.sol
protocol/contracts/libraries/Silo/LibTokenSilo.sol
protocol/contracts/libraries/Silo/LibWhitelist.sol
protocol/contracts/mocks/mockFacets/MockSeasonFacet.sol
protocol/contracts/mocks/mockFacets/MockSiloFacet.sol
protocol/test/foundry/farm/PipelineConvert.t.sol
protocol/test/foundry/invariantTesting/BeanstalkHandler.sol
protocol/test/foundry/silo/Whitelist.t.sol
protocol/test/foundry/sun/Flood.t.sol
protocol/test/foundry/utils/TestHelper.sol
protocol/test/hardhat/Convert.test.js
protocol/test/hardhat/ConvertUnripe.test.js
protocol/test/hardhat/Field.test.js
protocol/test/hardhat/Silo.test.js
protocol/test/hardhat/SiloEnroot.test.js
protocol/test/hardhat/SiloToken.test.js
protocol/test/hardhat/utils/helpers.js
protocol/test/hardhat/utils/testHelpers.js

The seed gauge update increased the precision of stems by 1e6. This introduced the ability for microStalk (fractions of 1 unit of stalk) to be deducted due to an integer division error.  By increasing the stalk precision by 1e6 (1 stalk = 1e16 stalk), this solves this issue.

implement stalk scale increase

---

protocol/abi/Beanstalk.json
protocol/contracts/libraries/Token/LibTransfer.sol
protocol/hardhat.config.js
protocol/test/hardhat/Token.test.js

Tracking Internal Balance transfers is difficult to do solely through events. For example, if a block contains multiple internal transfers, its impossible to deduce which transfer went to what, without directly looking at the transaction txs. This PR adds an event that emits the transfer modes when interacting with Farm balances.

add TokenTransferred event

---

projects/subgraph-bean/manifests/ethereum.yaml
projects/subgraph-bean/src/utils/Pool.ts
projects/subgraph-bean/src/utils/price/BeanstalkPrice.ts

Omits handling of events where the price contract reported zero values. This is preferable to avoid the liquidity values recording as 0 incorrectly

Bean subgraph - workaround for price contract irregularity

---

protocol/contracts/beanstalk/init/reseed/L2/ReseedBean.sol
protocol/reseed/reseed3.js
protocol/reseed/reseedDeployL2Beanstalk.js

- Add support to deploy all upgradeable well implementations in addition to their ERC1967 proxies from the same `ReseedBean` init script,  removing the need to be deployed from js.
- Add token addresses as constants in the init script

Bore wells from `ReseedBean`

---

projects/subgraph-beanstalk/src/handlers/GaugeHandler.ts
projects/subgraph-beanstalk/src/utils/Barn.ts
projects/subgraph-beanstalk/src/utils/Init.ts
projects/subgraph-beanstalk/src/utils/Yield.ts
projects/subgraph-beanstalk/tests/SeedGauge.test.ts

- Workaround for bug in `TotalGerminatingBalanceChanged` event emission
- Fix double counting of some stalk in vapy calculation
- Fix improper precision in chopped bdv calculation

subgraph-beanstalk misc fixes

---

protocol/contracts/beanstalk/silo/PipelineConvertFacet.sol
protocol/contracts/libraries/Convert/LibPipelineConvert.sol
protocol/test/foundry/farm/PipelineConvert.t.sol

Currently,`PipelineConvert` performs a set of advanced Farm Calls. With the recent security update, Farm functions cannot call other Farm functions. This means that pipelineConvert cannot be used in farm and tractor calls. This limits composability given that it limits the ability of tractor functionality. 
This PR replaces farm calls with pipe calls instead. Given that most, if not all previous functionally can be done with a pipelineConvert within a farm call.

update pipelineConvert to use pipecalls instead of advancedFarmCalls.

---

protocol/abi/Beanstalk.json
protocol/abi/MockBeanstalk.json
protocol/contracts/C.sol
protocol/contracts/beanstalk/farm/DepotFacet.sol
protocol/contracts/beanstalk/init/InitalizeDiamond.sol
protocol/contracts/beanstalk/silo/WhitelistFacet/WhitelistFacet.sol
protocol/contracts/beanstalk/storage/System.sol
protocol/contracts/beanstalk/sun/GaugePoints/GaugePointFacet.sol
protocol/contracts/beanstalk/sun/GaugePoints/GaugePointPrice.sol
protocol/contracts/beanstalk/sun/LiquidityWeightFacet.sol
protocol/contracts/beanstalk/sun/SeasonFacet/Sun.sol
protocol/contracts/interfaces/IMockFBeanstalk.sol
protocol/contracts/libraries/Convert/LibPipelineConvert.sol
protocol/contracts/libraries/LibEvaluate.sol
protocol/contracts/libraries/LibGauge.sol
protocol/contracts/libraries/LibIncentive.sol
protocol/contracts/libraries/Silo/LibWhitelist.sol
protocol/contracts/mocks/MockOracle.sol
protocol/contracts/mocks/mockFacets/MockSeasonFacet.sol
protocol/hardhat.config.js
protocol/test/foundry/silo/Whitelist.t.sol
protocol/test/foundry/sun/Flood.t.sol
protocol/test/foundry/sun/Gauge.t.sol

The Implementation struct was recently provides an generic bytes parameter that any implementation can use to provide data to a given Implementation Contract. This PR adds support for the GaugePoint and LiquidityWeight to use the generic bytes when calling the Implementation. This potentially allows for any implementation to be implemented without introducing new encoding types. 
Encode Types are kept in the instance where multiple Implementations share a common Interface, where the code can be upgraded to support different function signatures, but are not explicitly necessary. 
The various whitelisting functions were consolidated into a single whitelist function due to the redundancy that was 
Misc Changes. 
- Updates the DepotFacet to use C.PIPELINE, rather than defining pipeline in the …

Constants + Whitelist Update

---

protocol/contracts/libraries/Silo/LibFlood.sol
protocol/test/foundry/sun/Flood.t.sol

Converts would be more beneficial for Beanstalk than the system Flood the wells. Beanstalk should incentivize this action as much as possible, which is currently done when P > Q, but not when its about to flood. By adjusting Bean seeds as low as possible upon rain, the likelihood that a flood can be avoided is increased, as converts suddenly become more favorable.

Adjust seeds upon rain start

---

protocol/contracts/libraries/Oracle/LibUsdOracle.sol
protocol/contracts/libraries/Silo/LibWhitelist.sol
protocol/test/foundry/silo/Oracle.t.sol
protocol/test/foundry/silo/Whitelist.t.sol

T1MOH593 report [L-04] fix.
LibUsdOracle uses address(this) if target address is not specified:
However in sanity check during whitelist it will make call to address(0) which always succeeds instead of real sanity check (`function verifyOracleImplementation`)
This performs a similar check in `LibWhitelist.verifyOracleImplementation`.
Would've liked to have written a test for it, but it seems there's currently no way to fully exercise this code path due to no matching public selector available for use.

Fix LibWhitelist.verifyOracleImplementation() is inconsistent with LibUsdOracle.sol

---

protocol/contracts/beanstalk/sun/OracleFacet.sol
protocol/contracts/libraries/Oracle/LibChainlinkOracle.sol
protocol/contracts/libraries/Oracle/LibUniswapOracle.sol
protocol/contracts/libraries/Oracle/LibUsdOracle.sol
protocol/contracts/libraries/Well/LibWell.sol
protocol/test/foundry/Migration/L1Reciever.t.sol

Beanstalk currently calculates the DeltaB of a Well by calculating the difference in beans from the current ratio of the pool, to the target ratio of the pool. This is done by fetching the USD:TOKEN ratio for a given token. 
When this is done for a token that has 1) low decimals (<=8), and 2) a high price (5 figures or higher), this can lead to inaccuracies due to precision loss. 
This PR adds an option to fetch the MILLION_USD/TOKEN price for a given token, to increase the precision of the price.

Million USD Price.

---

protocol/contracts/beanstalk/migration/L1RecieverFacet.sol

fixes [M-05] from timo.
- ReseedGlobal sets internal balances that also reflect smart contract account balances. 
- When performing the migration, all assets are optimistically minted to the diamond address. 
- When smart contracts migrate their internal balance via the `L2MigrationFacet` and `L1RecieverFacet`, an amount of assets will be allocated to their delegated `receiver`. This does not need to trigger an increase in global internal balances as its already accounted for in `ReseedGlobal`. 
- This way the effectiveness of the `fundsSafu` invariant modifier will be preserved.

Fix: Set only individual receiver internal balance in `L1RecieverFacet`.

---

protocol/contracts/libraries/LibGauge.sol

Fixes [M-04] from timoh review.

Fix: Update `STALK_BDV_PRECISION` to new decimals. 

---

protocol/contracts/beanstalk/migration/L2MigrationFacet.sol

Fixes [M-03] from Timoh's review.
"In Arbitrum `excessFeeRefundAddress` is receiver of excess submission cost, worth noting is that excess fee is refunded on L2. https://docs.arbitrum.io/how-arbitrum-works/arbos/l1-l2-messaging#submission
Problem is that L2MigrationFacet.sol is explicitly assumed to be used by smart contracts which don't exist on L2. Therefore excess fee will be lost for them."

Fix: Set `excessFeeRefundAddress` to L2 receiver rather than L1 `msg.sender`

---

protocol/contracts/beanstalk/migration/L1RecieverFacet.sol

Fixes [M-02]: Usually there is no problem because activeField is 0 (old version). However if user waited so long such that activeField was updated, migration would corrupt storage.

Fix: Incorrect Plot issuance in case `activeField` is updated before user's migration

---

protocol/contracts/beanstalk/init/InitalizeDiamond.sol
protocol/contracts/beanstalk/silo/SiloFacet/SiloFacet.sol
protocol/contracts/beanstalk/sun/SeasonFacet/GaugeGettersFacet.sol
protocol/contracts/beanstalk/sun/SeasonFacet/SeasonFacet.sol
protocol/contracts/beanstalk/sun/SeasonFacet/SeasonGettersFacet.sol
protocol/contracts/libraries/LibEvaluate.sol
protocol/contracts/libraries/Silo/LibSiloPermit.sol
protocol/contracts/libraries/Silo/LibTokenSilo.sol
protocol/reseed/reseed10.js
protocol/scripts/deploy.js
protocol/scripts/diamond.js
protocol/test/foundry/sun/Gauge.t.sol
protocol/test/foundry/utils/BeanstalkDeployer.sol
protocol/test/hardhat/utils/tractor.js

With the Stalk Precision update (where stalk has 16 decimals instead of 10), the averageGrownStalkPerBDV is also increased by 6 decimals. The mock initialization did not correctly scale this value up (from 3e6 to 3e12). This PR fixes that, as well as fix the associated tests.

fix gauge point test.

---

protocol/contracts/beanstalk/silo/ConvertGettersFacet.sol
protocol/contracts/interfaces/IMockFBeanstalk.sol
protocol/contracts/mocks/mockFacets/MockPipelineConvertFacet.sol
protocol/test/foundry/farm/PipelineConvert.t.sol

Exposes the calculateDeltaBFromReserves function so that the frontend UI can use it to calculate how deltaB will be affected before/after swaps.

Expose calculateDeltaBFromReserves

---

protocol/contracts/beanstalk/silo/SiloFacet/SiloGettersFacet.sol
protocol/contracts/interfaces/IMockFBeanstalk.sol
protocol/test/foundry/Migration/ReseedState.t.sol

Ensures stalk number line up by being able to remove all deposits after reseed. Total number of accounts is 3665. I don't recommend running this test with the -vvvvv flag because it takes a long time to spit out the final output.

Test removing all deposits

---

protocol/contracts/beanstalk/init/reseed/L2/ReseedAccountStatus.sol

- Emission of `MigratedAccountStatus` and `MigratedAccountTokenStatus` events on a per account and per account, per token basis.

Update Reseed Account Status Events

---

protocol/hardhat.config.js
protocol/reseed/dataConverts/convertTokens.js
protocol/reseed/reseedL2.js

- Remove ownership claim and facet addition from reseedL2.
- Add facet addition to generate the diamond cut to a new task `reseedL2AddFacets`.
- Fix 3crv pool usdc name.

Final L2 deployment Tasks

---

protocol/contracts/beanstalk/ForkSystem/TransmitInFacet.sol
protocol/contracts/beanstalk/ForkSystem/TransmitOutFacet.sol
protocol/contracts/interfaces/IMockFBeanstalk.sol
protocol/contracts/interfaces/ITransmitInFacet.sol
protocol/contracts/interfaces/ITransmitOutFacet.sol
protocol/contracts/libraries/ForkSystem/LibTransmitOut.sol
protocol/contracts/libraries/Silo/LibGerminate.sol
protocol/contracts/tokens/Fertilizer/Fertilizer1155.sol
protocol/test/foundry/forkSystem/TransmitToFork.t.sol
protocol/test/foundry/sun/Flood.t.sol
protocol/test/foundry/utils/BeanstalkDeployer.sol
protocol/test/foundry/utils/LibAltC.sol

Updates TransmitInFacet to handle 2d bytes array for asset transmission flexibility.
(This PR will be updated to merge into the main transmission branch once the master merge branch is merged).
This also includes:
- Updates tests from using `require` to `assert`
- Adds test for `totalHarvested` and `totalSlashed`
- Disallows the transfer of germinating deposits
- Fixes TransmitOutFacet to pass through data from it's input param to the TransmitInFacet (bug fix)

Update transmit in facet to accept bytes array for asset flexibility
