readme.md
* New contract addresses primarily
=> README Replant updates

protocol/contracts/libraries/Oracle/LibCurveOracle.sol, protocol/test/Oracle.test.js
Per the process outlined in the [BCM Emergency Response Procedures](https://docs.bean.money/governance/beanstalk/bcm-process#emergency-response-procedures), an emergency hotfix may be implemented by an emergency vote of the BCM if the bug is minor and does not require significant code changes.
Note: Bugs or security vulnerabilities qualify as emergencies. Emergency action will not be taken for any reason related to the economic health of Beanstalk (like a bank run, for example).
* GitHub PR: https://github.com/BeanstalkFarms/Beanstalk/pull/92
* GitHub Commit Hash: 7168560db94426bbf736b4919a1ea4bccbdeab27
* Gnosis Transaction: https://etherscan.io/tx/0x1ca14810306dfcb098950137f58b53a4034fe0f097985ea2403ec9d5de467076
After the Ethereum merge occurs, multi-block …
=> EBIP-2: deltaB Cap

bips/bip-25.md, protocol/contracts/farm/init/InitMint.sol, protocol/scripts/diamond.js
* Mint 1,000,000 Beans to fund Beanstalk Farms to retain, grow and support a group of core contributors through the end of Q4 2022.
Beanstalk Farms designed the Q4 2022 budget to enable core contributors to work towards the following goals:
* Decentralized development: continue to develop a diverse organization without any single points of failure or dependence.
* Focus and flexibility: be able to deliver high quality output in a timely fashion, while having the flexibility to fund and support a wide variety of unique opportunities related to Beanstalk.
* Attracting high quality talent: continue to attract and retain high quality talent, which is critical to the success of Beanstalk.
Beanstalk was Unpaused on August 6, 2022 and the Q3 2022 budget of 500,000 Beans was …
=> BIP-25: Beanstalk Farms Q4 2022 Budget

bip-27.md
Bean Sprout
* Mint 100,000 Beans to fund Bean Sprout to seed, grow and support various Beanstalk-related integrations, projects, and initiatives through the end of Q4 2022.
TODO
* Launch at least one more Beanstalk-based company (_e.g._,begin development and raise capital)
* Focus on onboarding businesses and real world assets into the Beanstalk ecosystem
* Conduct a thorough customer discovery process
* Implement a Beanstalk custody solution
* Recruit world-class builders and businesses onto Beanstalk
* Finalize at least one wallet and banking partnership to support Beans such that the introduction of a Bean Card is possible alongside a seamless fiat to Beanstalk onramp
* Root product launches (pending audits, fingers crossed!)
* Fungible Deposited Bean-Denominated-Value ERC-20 Tokens
* …
=> BIP-27: Bean Sprout Q4 2022 Budget

projects/ui/src/components/Common/Charts/MultiLineChart.tsx
=> fix: x discontinuity on charts

projects/ui/src/components/Market/PodsV2/Tables/columns/market-columns.tsx
=> fix: add numerical sorting to pod marketplace tables

projects/ui/src/components/Market/PodsV2/Actions/Sell/FillOrderForm.tsx
=> fix: show bean balance even if destination is not selected

package.json, projects/cli/README.md, projects/cli/package.json, projects/cli/src/cli.ts
adds `--no-imp` flag which disables impersonation and allows connection to mainnet
Closes #234
=> cli: add flag to disable impersonation

projects/ui/src/components/Silo/SiloAssetApyChip.tsx
=> fix: apy chip pct

projects/examples/src/silo/claim-withdrawl.ts, projects/examples/src/silo/withdraw.ts, projects/sdk/src/lib/silo.ts, projects/sdk/src/lib/silo/Claim.ts
Adds:
- sdk.silo.claim()
- sdk.silo.claimSeasons()
- sdk.silo.getClaimableAmount()
=> SDK: Silo Claim

projects/examples/src/silo/deposit.ts, projects/examples/src/silo/transfer.ts, projects/sdk/src/lib/silo.ts, projects/sdk/src/lib/silo/Transfer.test.ts, projects/sdk/src/lib/silo/Transfer.ts, projects/sdk/src/utils/TestUtils/BlockchainUtils.ts, projects/sdk/src/utils/TestUtils/provider.ts
=> Silo transfer

projects/ui/src/components/Common/Charts/LineChart.tsx, projects/ui/src/components/Common/Charts/MultiLineChart.tsx, projects/ui/src/components/Common/Charts/StackedAreaChart.tsx
=> fix: new accounts cause crash when hovering over charts

projects/ui/src/components/Silo/Actions/Convert.tsx, projects/ui/src/components/Silo/Actions/Withdraw.tsx
=> UI: Remove extra plant() call on convert/withdraw

projects/ui/src/components/Silo/Actions/Deposits.stories.tsx
=> ui: fix build

projects/ui/src/util/Time.tsx
Fixed rounding issue when there's less than 48 hours to the end of the voting period
Addresses issue #324
=> Gov page: Fixed countdown rounding issue

projects/ui/src/components/Governance/Actions/Vote.tsx
=> fix: show 0 instead of NaN on gov page when nobody has voted

projects/sdk/package.json, projects/sdk/src/defaultSettings.json
- update graph URL
- release v0.1.0 (off of beta)
=> SDK: v0.1.0, update graph url

PROPOSALS.md
Proposer Wallet: [0x4fe7788deb22c548e57c4e95a365600ed377265b](https://etherscan.io/verifySig/13548)
* Mint 400,000 Beans to fund Beanstalk Farms to retain, grow and support a group of core contributors to Beanstalk through the end of Q1 2023;
* Mint 950,000 Beans to fund Beanstalk Farms through the end of Q2 2023;
* Mint 500,000 Beans to the Audit Fund; and
* Maintain the DAO's ability to withhold Beanstalk Farms' Q2 funding after the end of Q1 with an appropriate goverance structure.
* [BIP-33 GitHub PR](https://github.com/BeanstalkFarms/Beanstalk/pull/285)
* [Safe Transaction **UPDATE**](UPDATE)
* GitHub Commit Hash: [c94cf7aecab5175f5697ca2a1494a7df75713bc2](https://github.com/BeanstalkFarms/Beanstalk/pull/285/commits/c94cf7aecab5175f5697ca2a1494a7df75713bc2)
Beanstalk …
=> BIP-33: Beanstalk Farms H1 2023 Budget

projects/ui/src/components/Barn/Actions/Buy.tsx, projects/ui/src/components/Barn/Actions/Rinse.tsx, projects/ui/src/components/Chop/Actions/Chop.tsx, projects/ui/src/components/Common/Form/SmartSubmitButton.tsx, projects/ui/src/components/Common/TxnToast.tsx, projects/ui/src/components/Farmer/Unripe/PickDialog.tsx, projects/ui/src/components/Field/Actions/Harvest.tsx, projects/ui/src/components/Field/Actions/Sow.tsx, projects/ui/src/components/Field/Actions/Transfer.tsx, projects/ui/src/components/Governance/Actions/Vote.tsx, projects/ui/src/components/Market/PodsV2/Actions/Buy/CreateOrder.tsx, projects/ui/src/components/Market/PodsV2/Actions/Buy/FillListingForm.tsx, projects/ui/src/components/Market/PodsV2/Actions/Sell/CreateListing.tsx, projects/ui/src/components/Market/PodsV2/Actions/Sell/FillOrderForm.tsx, projects/ui/src/components/Silo/Actions/Claim.tsx, projects/ui/src/components/Silo/Actions/Convert.tsx, projects/ui/src/components/Silo/Actions/Deposit.tsx, projects/ui/src/components/Silo/Actions/Transfer.tsx, projects/ui/src/components/Silo/Actions/Withdraw.tsx, projects/ui/src/components/Silo/RewardsForm.tsx, projects/ui/src/components/Swap/Actions/Swap.tsx, projects/ui/src/constants/errors.ts, projects/ui/src/util/Ledger.ts
More robust error handling, should prevent the tall error toast from ever appearing
Enabled the ability to copy the full error string to clipboard if we can't find a proper reason for the error
Addresses #308 and #211
=> Improved error handling

projects/ui/src/components/Common/Tabs/index.tsx, projects/ui/src/components/Governance/Proposals/index.tsx
=> feat: Show the number of active proposals in governance page tabs

package.json, projects/subgraph-wells/abis/Aquifer.json, projects/subgraph-wells/abis/CurvePrice.json, projects/subgraph-wells/abis/Well.json, projects/subgraph-wells/schema.graphql, projects/subgraph-wells/src/WellHandler.ts, projects/subgraph-wells/src/templates/AquiferHandler.ts, projects/subgraph-wells/src/utils/Decimals.ts, projects/subgraph-wells/src/utils/Liquidity.ts, projects/subgraph-wells/src/utils/Token.ts, projects/subgraph-wells/src/utils/Well.ts, projects/subgraph-wells/subgraph.yaml, projects/subgraph-wells/tests/Well.test.ts, projects/subgraph-wells/tests/helpers/Aquifer.ts, projects/subgraph-wells/tests/helpers/Constants.ts, projects/subgraph-wells/tests/helpers/Functions.ts, projects/subgraph-wells/tests/helpers/Liquidity.ts, projects/subgraph-wells/tests/helpers/Swap.ts
Update handlers to calculate and save well amounts in USD. Current limitation on implementation is an expectation of a two token well.
=> Wells USD values

projects/ui/src/components/Market/PodsV2/Modules/MarketGraph.tsx
This fixes issues https://github.com/BeanstalkFarms/Beanstalk/issues/189.
It seems this file had a lot of prettier formatting changes that was not applied. I went ahead and applied it in a separate commit first in b45bf92141da51c0014e113dc4b21cda5be11c2f, so you can easily review the bug fixes. Moreover, you'll find a refactor commit after that in 6439fae3f2c2499b6dd9de39d93477265d512cba, which shows how I made the code more DRY which should help with readability/comprehension. Afterwards, you'll find the commits for the actual fix. I would advise going through each commit individually since I segmented each change with the reviewer in mind.
=> [ISSUE-189] UI Fixes and general code improvements

projects/ui/src/hooks/beanstalk/useMarketActivityData.ts
=> fix: discrepancy between pod market history values & actual values

projects/examples/src/wells/sampleData.ts
Re-introduce the sampleData script mistakenly deleted during rebase and force push.
=> Re-add sampledata script

projects/ui/src/components/Analytics/Bean/VolumeChart.tsx, projects/ui/src/components/Common/Charts/BarChart.tsx
Re-ran `yarn build` after the change in #369 to address errors
=> fix: typescript errors

projects/ui/src/pages/swap.tsx, projects/ui/src/util/Guides.ts
"How to Transfer Farm Balance" > "How to Transfer Balances"
=> Update copy for Transfer guide docs

projects/ui/src/util/Ledger.ts
Fixed error system not handling manually thrown exceptions correctly
=> Fixed error system not handling manual exceptions

projects/dex-ui/src/components/Liquidity/AddLiquidity.tsx, projects/dex-ui/src/pages/Well.tsx, projects/dex-ui/src/tokens/useWellTokens.tsx
=> Add liquidity component

projects/subgraph-wells/subgraph.yaml
Small issue with subgraph-wells.
=> Fix wells subgraph

projects/dex-ui/src/components/Liquidity/RemoveLiquidity.tsx, projects/dex-ui/src/components/Swap/BasicInput.tsx, projects/dex-ui/src/components/Swap/TokenInput.tsx, projects/dex-ui/src/pages/Well.tsx
Remove liquidity:
- balanced (50/50 ratio)
- one token
- custom ratio
=> Remove liquidity balanced one token and custom

projects/dex-ui/src/components/Liquidity/AddLiquidity.tsx, projects/dex-ui/src/components/Liquidity/RemoveLiquidity.tsx, projects/dex-ui/src/components/Liquidity/types.ts, projects/dex-ui/src/pages/Well.tsx, projects/dex-ui/src/wells/useLiquidityQuote.tsx
Feedback from PR https://github.com/BeanstalkFarms/Beanstalk/pull/413
=> Feedback from earlier PR

projects/dex-ui/src/components/Liquidity/AddLiquidity.tsx, projects/dex-ui/src/components/Liquidity/RemoveLiquidity.tsx, projects/sdk-wells/src/lib/Well.ts
=> wells-sdk: add gas estimation

projects/ui/src/pages/nft.tsx, projects/ui/src/util/BeaNFTs.ts
=> Updated BeaNFT page to use latest subgraph schema

projects/dex-ui/.env.local.example, projects/dex-ui/src/assets/images/arrow.svg, projects/dex-ui/src/assets/images/info.svg, projects/dex-ui/src/components/Liquidity/AddLiquidity.tsx, projects/dex-ui/src/components/Liquidity/LiquidityRoot.tsx, projects/dex-ui/src/components/Liquidity/RemoveLiquidity.tsx, projects/dex-ui/src/components/Liquidity/SlippagePanel.tsx, projects/dex-ui/src/components/Liquidity/allowance.ts, projects/dex-ui/src/components/Liquidity/useEthPrice.tsx, projects/dex-ui/src/components/Swap/TokenInput.tsx, projects/dex-ui/src/pages/Well.tsx, projects/examples/src/wells/revoke-approval.ts
=> Update add liquidity to reflect design

projects/ui/src/lib/Beanstalk/Governance.ts, projects/ui/src/pages/governance/proposal.tsx, projects/ui/src/util/Governance.ts
=> Governance Page updates

projects/ui/src/components/Field/Actions/Sow.tsx, projects/ui/src/lib/Txn/FarmSteps/field/SowFarmStep.ts, yarn.lock
Fixes the issue in the Sow Module where if the user is sowing using only Claimed Beans & the input token is not BEAN
=> Fix Sow With Claimable Beans

projects/ui/src/components/Common/Form/PlotSelect.tsx
Alignment and color fixes to the Plot Select dialog in multi-selection mode
=> Multi Plot Select formatting tweaks

projects/ui/src/components/Common/MarkdownWrapper.tsx
Changed styling of text links on governance proposal pages
=> Markdown text link styling change

projects/examples/src/dex/deploy.ts, projects/examples/src/dex/loadWells.ts, projects/sdk-wells/src/constants/abi/GenericWellFunction.json, projects/sdk-wells/src/lib/Aquifer.ts, projects/sdk-wells/src/lib/Well.ts, projects/sdk-wells/src/lib/WellFunction.ts, projects/sdk-wells/test/addliquidity.test.ts, projects/sdk-wells/test/removeliquidity.test.ts, projects/sdk-wells/test/swap.test.ts, projects/sdk-wells/test/well.test.ts
adds ability to deploy a well, via an aquifer, to the SDK.
=> sdk-well: deploy well through aquifer

projects/dex-ui/src/components/Liquidity/AddLiquidity.tsx, projects/dex-ui/src/components/Liquidity/QuoteDetails.tsx, projects/dex-ui/src/components/Liquidity/RemoveLiquidity.tsx, projects/dex-ui/src/wells/useWellReserves.tsx
Added useWellReserves query to ensure we're always using the latest data
Fixed crash when tokenPrices are undefined
=> Basin UI - Well reserves query

projects/dex-ui/src/components/Swap/BasicInput.tsx, projects/dex-ui/src/components/Swap/SwapRoot.tsx, projects/dex-ui/src/components/Swap/TokenInput.tsx, projects/dex-ui/src/components/Swap/TokenPicker.tsx, projects/examples/src/setup.ts, projects/sdk-wells/src/lib/Well.ts, projects/sdk-wells/src/lib/utils.ts
- debounce TokenInput
- allow adding liquidity with just one token having a non-zero value
- some cleanup/fixes on the Swap page
=> Dex: fixes

projects/ui/src/components/Barn/Actions/Buy.tsx, projects/ui/src/components/Field/Actions/Sow.tsx, projects/ui/src/components/Silo/Actions/Deposit.tsx
Fix for Typescript error in new approval check code
=> Bean UI - Fix Typescript error in approval check

projects/ui/src/components/Governance/Actions/Vote.tsx
Fixed incorrect button text when user doesn't have Stalk/BeaNFTs to vote
=> Bean UI - Governance page button text logic fix

projects/ui/src/components/Governance/Actions/Vote.tsx
Adds supermajority (66.7%) display to BIP votes
=> Bean UI - Add supermajority display to BIP votes

projects/ui/package.json, projects/ui/src/components/Barn/Actions/Buy.tsx, projects/ui/src/components/Field/Actions/Sow.tsx, projects/ui/src/components/Silo/Actions/Migrate.tsx, projects/ui/src/components/Silo/Actions/Transfer.tsx, projects/ui/src/components/Silo/Actions/Withdraw.tsx, projects/ui/src/components/Silo/Actions/index.tsx, projects/ui/src/components/Silo/MigrateTab.tsx, projects/ui/src/components/Silo/Overview.tsx, projects/ui/src/hooks/farmer/useFarmerSiloBalanceSdk.ts, projects/ui/src/pages/silo/index.tsx, projects/ui/src/state/farmer/silo/actions.ts, projects/ui/src/state/farmer/silo/index.ts, projects/ui/src/state/farmer/silo/reducer.ts, projects/ui/src/state/farmer/silo/updater.ts, yarn.lock
Fix Typescript errors reintroduced in Silo V3 update
=> Bean UI - Fix Typescript errors

projects/ui/src/components/Market/PodsV2/Actions/Buy/FillListingForm.tsx
Fixed bug in pod marketplace that would appear when users tried to enter an input value
=> Bean UI - Fixed Fill Listing input bug

projects/ui/src/components/Analytics/Silo/index.tsx, projects/ui/src/components/Common/Connection/WalletButton.tsx, projects/ui/src/components/Common/Form/FormTxn/AddPlantTxnToggle.tsx, projects/ui/src/components/Common/Form/FormTxnOptionCard.tsx, projects/ui/src/components/Common/StatsCard.tsx, projects/ui/src/components/Common/Table/cells.tsx, projects/ui/src/components/Forecast/LiquidityByState.tsx, projects/ui/src/components/Silo/Actions/Migrate.tsx, projects/ui/src/components/Silo/Actions/Withdraw.tsx, projects/ui/src/components/Silo/MigrateTab.tsx, projects/ui/src/hooks/beanstalk/useBeanstalkBalancesBreakdown.tsx, projects/ui/src/hooks/farmer/form-txn/useFarmerFormTxnsSummary.ts, projects/ui/src/util/Actions.ts
Disabled History page
Disabled Seed Supply analytics
Various copy fixes and tweaks
=> Bean UI - Disabled broken pages/components + Copy updates

projects/ui/src/components/Silo/Actions/Migrate.tsx, projects/ui/src/components/Silo/Actions/index.tsx, projects/ui/src/components/Silo/MigrateTab.tsx, projects/ui/src/pages/silo/index.tsx
=> Bean UI - More copy tweaks

projects/dex-ui/src/components/BottomDrawer.tsx, projects/dex-ui/src/pages/Well.tsx
Removed return value on the callback ref
Fixed BottomDrawer's background appearing on desktop resolutions
=> Dex UI - Fixes

protocol/contracts/beanstalk/metadata/MetadataFacet.sol, protocol/contracts/beanstalk/metadata/MetadataImage.sol, protocol/test/Silo.test.js
=> Fix metadata remediations

projects/dex-ui/index.html, projects/dex-ui/src/components/App/OnLoad.tsx, projects/dex-ui/src/components/Frame/Footer.tsx, projects/dex-ui/src/components/Liquidity/AddLiquidity.tsx, projects/dex-ui/src/components/Well/Activity/eventRender.tsx
- update title
- fix swaps total in activity section
- update contribute link in footer
- fix weird reload loop bug
- fix price bug
=> Dex updates 2

projects/ui/src/components/Silo/SiloAssetApyChip.tsx, projects/ui/src/graph/queries/LatestAPY.graphql, projects/ui/src/hooks/beanstalk/useAPY.ts
=> Bean UI - Fix vAPY display

projects/ui/src/components/Analytics/Silo/APY.graphql, projects/ui/src/components/Analytics/Silo/APY.tsx, projects/ui/src/components/Analytics/Silo/index.tsx
Removed Bean/LP vAPY charts
Added 0/3/3.25/4.5 Seed Bean vAPY chart
Added Deposited BEANETH chart
=> Bean UI - Updated Analytics with new data

projects/ui/src/components/Common/Balances/BeanstalkBalances.tsx, projects/ui/src/components/Common/Balances/TokenRow.tsx
Pie chart will now show USD values
BDV and Token Amount will appear when hovering the USD value
=> Bean UI - Updated Pie chart to show USD values

projects/ui/src/lib/Txn/FarmSteps/silo/DepositFarmStep.ts
A Deposit would fail if the user tried to use only their Claimed Beans (ie: input amount is 0) and the selected token wasn't Bean
=> Bean UI - Fixed cBean-only deposits

projects/ui/src/components/App/SdkProvider.tsx, projects/ui/src/components/Nav/SettingsDialog.tsx, projects/ui/src/pages/field.tsx, projects/ui/src/state/app/index.ts, projects/ui/src/state/app/reducer.ts, projects/ui/src/state/farmer/field/actions.ts, projects/ui/src/state/farmer/field/index.ts, projects/ui/src/state/farmer/field/reducer.ts, projects/ui/src/state/farmer/field/updater.ts, projects/ui/src/state/farmer/silo/updater.ts
- adds settings for data source (to address rpc issues)
- adds loader to field page
=> data source settings

.github/workflows/ci.ui.yaml, projects/ui/src/components/Swap/Actions/Swap.tsx
Fixed error when entering values starting with a "." like ".01"
=> Bean UI - Fixed input error on Swap page

projects/ui/src/components/Governance/Actions/Vote.tsx
Enabled "Vote on Snapshot.org" button
=> Bean UI - Vote form tweaks

projects/ui/src/components/Silo/Actions/Transfer.tsx, projects/ui/src/pages/silo/index.tsx
=> UI: Show warning when silo migration is needed

protocol/contracts/C.sol, protocol/contracts/beanstalk/silo/SiloFacet/Silo.sol, protocol/contracts/beanstalk/sun/SeasonFacet/Weather.sol, protocol/contracts/libraries/LibEvaluate.sol, protocol/test/Sop.test.js
Changes to SOP changes:
- update claimPlenty to use the SOP token
- update SeasonOfPlenty event to include well/token
- update ClaimPlenty event to include token
- use min of sopBeans instead of beansAtPeg
- update variable names
=> Sop Updates

projects/dex-ui/package.json, projects/dex-ui/src/components/Liquidity/AddLiquidity.tsx, projects/dex-ui/src/tokens/useAllTokenBalance.tsx, projects/dex-ui/src/tokens/useLPPositionSummary.tsx, projects/dex-ui/src/tokens/useSiloBalance.tsx, projects/dex-ui/src/tokens/useTokenBalance.tsx, projects/dex-ui/src/tokens/useTokenBalanceInternal.tsx, projects/dex-ui/src/tokens/useTokenSupply.tsx, projects/dex-ui/src/tokens/useWellTokens.tsx, projects/dex-ui/src/wells/useBeanstalkSiloAPYs.tsx, projects/dex-ui/src/wells/useLiquidityQuote.tsx, projects/dex-ui/src/wells/useMultiFlowPumpTWAReserves.tsx, projects/dex-ui/src/wells/useWell.tsx, projects/dex-ui/src/wells/useWellChartData.tsx, projects/dex-ui/src/wells/useWellHistory.tsx, projects/dex-ui/src/wells/useWellReserves.tsx, projects/dex-ui/src/wells/useWells.tsx, projects/dex-ui/tsconfig.json, yarn.lock
=> dex: upgrade react-query to fix bug

protocol/abi/Beanstalk.json, protocol/contracts/libraries/Silo/LibGerminate.sol, protocol/contracts/libraries/Silo/LibSilo.sol, protocol/contracts/mocks/mockFacets/MockSeasonFacet.sol, protocol/test/Silo.test.js, protocol/test/Sun.test.js, yarn.lock
- removes unneeded stalk burn function.
=> Add libGerminate Event

protocol/contracts/beanstalk/init/InitalizeDiamond.sol, protocol/contracts/interfaces/IMockFBeanstalk.sol, protocol/contracts/libraries/LibLockedUnderlying.sol, protocol/contracts/mocks/chainlink/MockChainlinkAggregator.sol, protocol/contracts/mocks/mockFacets/MockSeasonFacet.sol, protocol/contracts/mocks/newMockInitDiamond.sol, protocol/test/Gauge.test.js, protocol/test/foundry/sun/Gauge.t.sol, protocol/test/foundry/sun/Sun.t.sol, protocol/test/foundry/utils/TestHelper.sol
- adds gauge tests
- adds additional helper functions.
- updates LibLockedUnderlying.
=> gauge tests

protocol/contracts/C.sol, protocol/contracts/beanstalk/silo/L2ContractMigrationFacet.sol
Implements the ability for an L1 contract to migrate deposits into L2.
=> L2ContractMigrationFacet

projects/ui/src/components/Nav/Buttons/PriceButton.tsx, projects/ui/src/components/Silo/PoolCard.tsx, projects/ui/src/components/Silo/RewardsSummary.tsx
=> price button copy edits

protocol/contracts/beanstalk/Invariable.sol, protocol/contracts/beanstalk/barn/FertilizerFacet.sol, protocol/contracts/beanstalk/field/FieldFacet.sol, protocol/contracts/beanstalk/init/InitDistribution.sol, protocol/contracts/beanstalk/storage/System.sol, protocol/contracts/beanstalk/sun/SeasonFacet/Distribution.sol, protocol/contracts/beanstalk/sun/SeasonFacet/Receiving.sol, protocol/contracts/ecosystem/ShipmentPlanner.sol, protocol/contracts/interfaces/IMockFBeanstalk.sol, protocol/contracts/interfaces/IShipmentPlanner.sol, protocol/contracts/mocks/mockFacets/MockAdminFacet.sol, protocol/contracts/mocks/mockFacets/MockSeasonFacet.sol, protocol/test/foundry/field/Field.t.sol, protocol/test/foundry/sun/Gauge.t.sol, protocol/test/foundry/sun/Sun.t.sol, protocol/test/foundry/utils/BeanstalkDeployer.sol, protocol/test/foundry/utils/ShipmentDeployer.sol, protocol/test/foundry/utils/TestHelper.sol, protocol/test/foundry/utils/Utils.sol
fix forge tests and the logic they test. all forge tests pass. some hardhat tests fail on unrelated logic from unrelated merges.
=> Field secure fixes

projects/ui/src/components/Silo/Whitelist.tsx
=> bug: incorrect apy copy

projects/dex-ui/src/components/Button.tsx, projects/dex-ui/src/components/Create/ChooseComponentNames.tsx, projects/dex-ui/src/components/Create/ChooseFunctionAndPump.tsx, projects/dex-ui/src/components/Create/ChooseWellImplementation.tsx, projects/dex-ui/src/components/Create/ComponentLibraryTable.tsx, projects/dex-ui/src/components/Create/CreateWellPreviewDeploy.tsx, projects/dex-ui/src/components/Create/CreateWellProvider.tsx, projects/dex-ui/src/components/Create/shared/ComponentAccordionCard.tsx, projects/dex-ui/src/components/Create/shared/CreateWellButtonRow.tsx, projects/dex-ui/src/components/Create/shared/CreateWellFormProgress.tsx, projects/dex-ui/src/components/Dialog.tsx, projects/dex-ui/src/components/Form.tsx, projects/dex-ui/src/components/PageComponents/Title.tsx, projects/dex-ui/src/components/ProgressCircle.tsx, projects/dex-ui/src/components/Typography/Text.tsx, projects/dex-ui/src/components/Typography/typography-components.tsx, projects/dex-ui/src/pages/Build.tsx, projects/dex-ui/src/pages/Create.tsx
- mobile improvements
- bore well deploy dialog + navigation on successful deploy
=> feat: [Dex-ui/well-creator]: UI improvements

projects/subgraph-beanstalk/schema.graphql, projects/subgraph-beanstalk/src/GaugeHandler.ts, projects/subgraph-beanstalk/src/SeasonHandler.ts, projects/subgraph-beanstalk/src/YieldHandler.ts, projects/subgraph-beanstalk/src/utils/Beanstalk.ts, projects/subgraph-beanstalk/src/utils/Germinating.ts, projects/subgraph-beanstalk/src/utils/Season.ts, projects/subgraph-beanstalk/subgraph.yaml, projects/subgraph-beanstalk/tests/YieldHandler.test.ts
- Add `blockNumber` of the sunrise to `Season` entity
- Added fields to improve queryability of `Germinating` entity
- Fix stalk apy recording excessively high values
=> [Beanstalk Subgraph] Misc improvements and fixes

protocol/contracts/libraries/Convert/LibUnripeConvert.sol, protocol/contracts/libraries/LibBarnRaise.sol, protocol/contracts/libraries/LibFertilizer.sol, protocol/contracts/libraries/Oracle/LibOracleHelpers.sol, protocol/contracts/libraries/Oracle/LibUsdOracle.sol, protocol/contracts/libraries/Oracle/LibWstethEthOracle.sol, protocol/test/WstethOracle.test.js
Reverts BeanstalkFarms/Beanstalk#922
=> Revert "wstETH Migration Remediations"

projects/dex-ui/src/components/BottomDrawer.tsx, projects/dex-ui/src/components/Frame/TokenMarquee.tsx, projects/dex-ui/src/components/Swap/SwapRoot.tsx, projects/dex-ui/src/components/Swap/TokenInput.tsx, projects/dex-ui/src/components/Swap/TokenPicker.tsx, projects/dex-ui/src/components/Swap/useSwapBuilder.tsx, projects/dex-ui/src/components/TokenLogo.tsx, projects/dex-ui/src/components/Well/LearnPump.tsx, projects/dex-ui/src/components/Well/LearnWellFunction.tsx, projects/dex-ui/src/components/Well/LearnYield.tsx, projects/dex-ui/src/components/Well/Reserves.tsx, projects/dex-ui/src/components/Well/Table/WellDetailRow.tsx, projects/dex-ui/src/pages/Liquidity.tsx, projects/dex-ui/src/pages/Well.tsx, projects/dex-ui/src/token-metadata.json, projects/dex-ui/src/tokens/TokenProvider.tsx, projects/dex-ui/src/types.tsx, projects/dex-ui/src/utils/format.ts, projects/dex-ui/src/utils/token/useTokenMetadata.ts, projects/dex-ui/src/wells/useBeanstalkSiloWhitelist.ts, projects/dex-ui/src/wells/useWells.tsx, projects/dex-ui/src/wells/utils.ts
=> bugs: [dex-ui]: Post Well Creator cleanup

protocol/contracts/libraries/Convert/LibUnripeConvert.sol, protocol/contracts/libraries/LibBarnRaise.sol, protocol/contracts/libraries/LibFertilizer.sol, protocol/contracts/libraries/Oracle/LibOracleHelpers.sol, protocol/contracts/libraries/Oracle/LibUsdOracle.sol, protocol/contracts/libraries/Oracle/LibWstethEthOracle.sol, protocol/test/WstethOracle.test.js
=> Revert "Revert "wstETH Migration Remediations""

projects/dex-ui/src/components/Well/Chart/Chart.tsx, projects/dex-ui/src/components/Well/Chart/ChartSection.tsx, projects/ui/src/components/Analytics/ChartV2.tsx, projects/ui/src/components/Analytics/useChartSetupData.tsx, projects/ui/src/components/Governance/Proposal/index.tsx, projects/ui/src/components/Silo/Actions/Deposit.tsx, projects/ui/src/components/Silo/Whitelist.tsx, projects/ui/src/components/Swap/Actions/Swap.tsx, projects/ui/src/components/Swap/Actions/Transfer.tsx, projects/ui/src/hooks/beanstalk/useBalancesUsedBySource.ts, projects/ui/src/lib/Beanstalk/Silo/Deposit.ts, projects/ui/src/state/bean/unripe/index.ts, projects/ui/src/state/bean/unripe/updater.ts, projects/ui/src/util/Actions.ts, projects/ui/src/util/Tokens.ts, projects/ui/src/util/UI.ts
In this PR:
- Fixes rounding of BIP vote progress
- L2SR tooltip
- update SEED Decimals + BDV tooltip
- specify which balance amounts are coming from
- Fix 'all' time series chart data on Basin
- Fix urBEAN:WETH LP tooltip
=> [WIP]: bug-fix: [UI]: misc bugs

projects/ui/src/components/Governance/Actions/Vote.tsx
=> feat: [ui/Governance]: update display pct

protocol/contracts/beanstalk/sun/OracleFacet.sol, protocol/contracts/libraries/Oracle/LibUsdOracle.sol, protocol/test/foundry/silo/Oracle.t.sol, protocol/test/foundry/utils/OracleDeployer.sol
=> Oracle facet

protocol/contracts/beanstalk/migration/L1RecieverFacet.sol, protocol/contracts/beanstalk/migration/L2MigrationFacet.sol, protocol/contracts/libraries/LibDibbler.sol, protocol/contracts/libraries/LibIncentive.sol, protocol/test/foundry/Migration/ReseedMigrateL2.t.sol
Updates some variables to fit with the L2.
=> Implement L2

protocol/contracts/interfaces/basin/IBeanstalkWellFunction.sol, protocol/contracts/interfaces/basin/pumps/IMultiFlowPumpWellFunction.sol, protocol/contracts/libraries/LibEvaluate.sol, protocol/contracts/libraries/Well/LibWell.sol, protocol/contracts/mocks/well/MockPump.sol, protocol/test/foundry/utils/BasinDeployer.sol
Support any well function rather than just constant product 2.
=> Use calcRate in getBeanTokenPriceFromTwaReserves

projects/sdk/src/lib/silo.ts, projects/sdk/src/queries/silo/getSiloBalance.graphql, projects/sdk/src/queries/silo/getSiloBalances.graphql, projects/sdk/src/queries/silo/getSiloWhitelist.graphql, projects/ui/src/graph/schema-bean.graphql, projects/ui/src/graph/schema-beanft.graphql, projects/ui/src/graph/schema-snapshot1.graphql, projects/ui/src/hooks/beanstalk/useDataFeedTokenPrices.ts, projects/ui/src/util/wagmi/chains.ts, projects/ui/src/util/wagmi/config.ts
Fix RPC url falling back to cloudflare-eth
Fix TWA non-bean assets
=> Spacebean/UI dex UI/bugs

protocol/contracts/libraries/Oracle/LibUsdOracle.sol
- When a token whitelisted in the silo uses an uniswap Oracle Implementation, the price was calculated improperly when getting the USD/TOKEN price. 
The function now properly queries the chainlink oracle with proper decimal precision and returns the proper scaling.
=> fix oracle.

protocol/contracts/beanstalk/storage/System.sol
Removes unused vars as found in L-02 from auditor [T1MOH593](https://github.com/T1MOH593)
=> Remove unused storage vars

protocol/contracts/libraries/Well/LibWell.sol
Addresses [M-07] from timoh review.
=> Fix: `calculateTokenBeanPriceFromReserves` incorrect conditional.

protocol/contracts/libraries/LibDibbler.sol
=> Fix: Temperature if ladder incorrect value for `delta=1`

projects/ui/src/components/Silo/Token/DepositConvertTable.tsx, projects/ui/src/components/Silo/Token/TokenLambdaConvert.tsx
This PR:
- properly adds stalk and seeds to total stalk and seeds. 
- properly shows seed values.
- adds decimals to stalk
- shortens deposit ids
=> update lamda_lambda UI

protocol/test/foundry/Migration/ReseedState.t.sol
Exercises the `< C.WELL_MINIMUM_BEAN_BALANCE` path
=> Add a low liquidity convert test

protocol/contracts/libraries/Well/LibWell.sol
When Beanstalk has a positive non-zero deltaB, and the biggest liquidity well (via the twa) removes all its liquidity, the well Function fails. This can lead to the sunrise bricking. This PR fixes that edge case.
=> fix edge case by returning gracefully.
